---
platform: linux

image_resource:
  type: docker-image
  source: {repository: node, tag: "6" }

inputs:
- name: project-src
- name: project-src-cache

outputs:
- name: project-dist
  path: dist

run:
  path: concourse/build.sh
  dir: project-src