---
platform: linux

image_resource:
  type: docker-image
  source: {repository: node, tag: "6" }

inputs:
- name: project-src
  path: .
- name: node_modules

outputs:
- name: project-dist
  path: dist


run:
  path: npm
  args: [ run build ]