---
platform: linux

image_resource:
  type: docker-image
  source: {repository: node, tag: "6" }

inputs:
- name: project-working-dir

outputs:
- name: project-package

run:
  path: concourse/build.sh
  dir: project-working-dir